name: spice
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=1.5,<3
  - r-base=4.2
  - r-ape
  - r-coda
  - r-janitor
  - r-posterior>=1.6
  - r-dplyr
  - r-progress
  - r-phangorn
  - r-phytools
  - r-ggplot2
  - r-ggsci
  - r-biocmanager
